[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license-file.workspace = true

[dependencies]
gel-core = { path = "../crates/gel-core" }
gel-live-lab = { path = "../crates/gel-live-lab" }
gel-phase-quad = { path = "../crates/gel-phase-quad" }
gel-source = { path = "../crates/gel-source" }

[lints]
workspace = true
